model:
  name: Customized("../../models/siren/siren.py", "Siren")
  path: models/siren/siren.pth
data:
  dataset: MNIST
  end: 20
specification:
  norm: .inf
  epsilon: 0.3
solver:
  batch_size: 2048
  alpha-crown:
    lr_decay: 0.999
    iteration: 200
  beta-crown:
    lr_alpha: 0.5
    lr_beta: 0.1
    iteration: 10
bab:
  branching:
    method: nonlinear
    candidates: 3
    nonlinear_split:
      num_branches: 3
      method: babsr_like